### ISSUE TITLE
HDFS table path

### ISSUE THREAD

**Issue by jccaleroe** [delta-io/delta-sharing#112]
Greetings,

I have configured the server yaml to serve this HDFS delta file:

shares:
- name: "share1"
  schemas:
  - name: "schema1"
    tables:
    - name: "delta-table"
      location: "hdfs://localhost/user/juan/delta-table"

But when I try to load the file table, I get the following error:

160985 [armeria-common-worker-epoll-2-2] ERROR io.delta.sharing.server.DeltaSharingServiceExceptionHandler - com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: File system class **org.apache.hadoop.hdfs.DistributedFileSystem is not supported**

So, my question is if HDFS is really not support or I am missing something in the server configuration.

Thanks a lot!

**Comment by zsxwing** [comment]
HDFS is not supported. Currently the storage systems supported are AWS S3, Azure Blog Storage, Azure Data Lake Gen2, and Google Cloud Storage.

**Comment by zsxwing** [comment]
Closing this as it's answered. Feel free to re-open it if you have more questions.

**Comment by ThachNgocTran** [comment]
I think HDFS is not supported because Delta Sharing leverages the feature "[Presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)", which is not available in HDFS (to my knowledge). The reason to use this feature is that we delegate the serving/sending of data to Data Storage Providers (e.g. AWS S3, Azure Blob...), preventing Delta Sharing Server from becoming the bottle neck.

That said, the _actual_ data don't come through Delta Sharing Server; it only authorizes the requests.
